/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 * http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

package com.ibm.cos.v2.services.sts.model;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.BiConsumer;
import java.util.function.Function;
import com.ibm.cos.v2.annotations.Generated;
import com.ibm.cos.v2.annotations.Mutable;
import com.ibm.cos.v2.annotations.NotThreadSafe;
import com.ibm.cos.v2.core.SdkField;
import com.ibm.cos.v2.core.SdkPojo;
import com.ibm.cos.v2.core.protocol.MarshallLocation;
import com.ibm.cos.v2.core.protocol.MarshallingType;
import com.ibm.cos.v2.core.traits.LocationTrait;
import com.ibm.cos.v2.utils.ToString;
import com.ibm.cos.v2.utils.builder.CopyableBuilder;
import com.ibm.cos.v2.utils.builder.ToCopyableBuilder;

/**
 * <p>
 * The identifiers for the temporary security credentials that the operation returns.
 * </p>
 */
public final class AssumedRoleUser implements SdkPojo, Serializable, ToCopyableBuilder<AssumedRoleUser.Builder, AssumedRoleUser> {
    private static final SdkField<String> ASSUMED_ROLE_ID_FIELD = SdkField.<String> builder(MarshallingType.STRING)
                                                                          .memberName("AssumedRoleId").getter(getter(AssumedRoleUser::assumedRoleId)).setter(setter(Builder::assumedRoleId))
                                                                          .traits(LocationTrait.builder().location(MarshallLocation.PAYLOAD).locationName("AssumedRoleId").build()).build();

    private static final SdkField<String> ARN_FIELD = SdkField.<String> builder(MarshallingType.STRING).memberName("Arn")
                                                              .getter(getter(AssumedRoleUser::arn)).setter(setter(Builder::arn))
                                                              .traits(LocationTrait.builder().location(MarshallLocation.PAYLOAD).locationName("Arn").build()).build();

    private static final List<SdkField<?>> SDK_FIELDS = Collections.unmodifiableList(Arrays.asList(ASSUMED_ROLE_ID_FIELD,
                                                                                                   ARN_FIELD));

    private static final Map<String, SdkField<?>> SDK_NAME_TO_FIELD = memberNameToFieldInitializer();

    private static final long serialVersionUID = 1L;

    private final String assumedRoleId;

    private final String arn;

    private AssumedRoleUser(BuilderImpl builder) {
        this.assumedRoleId = builder.assumedRoleId;
        this.arn = builder.arn;
    }

    /**
     * <p>
     * A unique identifier that contains the role ID and the role session name of the role that is being assumed. The
     * role ID is generated by Amazon Web Services when the role is created.
     * </p>
     *
     * @return A unique identifier that contains the role ID and the role session name of the role that is being
     *         assumed. The role ID is generated by Amazon Web Services when the role is created.
     */
    public final String assumedRoleId() {
        return assumedRoleId;
    }

    /**
     * <p>
     * The ARN of the temporary security credentials that are returned from the <a>AssumeRole</a> action. For more
     * information about ARNs and how to use them in policies, see <a
     * href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html">IAM Identifiers</a> in the
     * <i>IAM User Guide</i>.
     * </p>
     *
     * @return The ARN of the temporary security credentials that are returned from the <a>AssumeRole</a> action. For
     *         more information about ARNs and how to use them in policies, see <a
     *         href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html">IAM Identifiers</a> in
     *         the <i>IAM User Guide</i>.
     */
    public final String arn() {
        return arn;
    }

    @Override
    public Builder toBuilder() {
        return new BuilderImpl(this);
    }

    public static Builder builder() {
        return new BuilderImpl();
    }

    public static Class<? extends Builder> serializableBuilderClass() {
        return BuilderImpl.class;
    }

    @Override
    public final int hashCode() {
        int hashCode = 1;
        hashCode = 31 * hashCode + Objects.hashCode(assumedRoleId());
        hashCode = 31 * hashCode + Objects.hashCode(arn());
        return hashCode;
    }

    @Override
    public final boolean equals(Object obj) {
        return equalsBySdkFields(obj);
    }

    @Override
    public final boolean equalsBySdkFields(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof AssumedRoleUser)) {
            return false;
        }
        AssumedRoleUser other = (AssumedRoleUser) obj;
        return Objects.equals(assumedRoleId(), other.assumedRoleId()) && Objects.equals(arn(), other.arn());
    }

    /**
     * Returns a string representation of this object. This is useful for testing and debugging. Sensitive data will be
     * redacted from this string using a placeholder value.
     */
    @Override
    public final String toString() {
        return ToString.builder("AssumedRoleUser").add("AssumedRoleId", assumedRoleId()).add("Arn", arn()).build();
    }

    public final <T> Optional<T> getValueForField(String fieldName, Class<T> clazz) {
        switch (fieldName) {
            case "AssumedRoleId":
                return Optional.ofNullable(clazz.cast(assumedRoleId()));
            case "Arn":
                return Optional.ofNullable(clazz.cast(arn()));
            default:
                return Optional.empty();
        }
    }

    @Override
    public final List<SdkField<?>> sdkFields() {
        return SDK_FIELDS;
    }

    @Override
    public final Map<String, SdkField<?>> sdkFieldNameToField() {
        return SDK_NAME_TO_FIELD;
    }

    private static Map<String, SdkField<?>> memberNameToFieldInitializer() {
        Map<String, SdkField<?>> map = new HashMap<>();
        map.put("AssumedRoleId", ASSUMED_ROLE_ID_FIELD);
        map.put("Arn", ARN_FIELD);
        return Collections.unmodifiableMap(map);
    }

    private static <T> Function<Object, T> getter(Function<AssumedRoleUser, T> g) {
        return obj -> g.apply((AssumedRoleUser) obj);
    }

    private static <T> BiConsumer<Object, T> setter(BiConsumer<Builder, T> s) {
        return (obj, val) -> s.accept((Builder) obj, val);
    }

    @Mutable
    @NotThreadSafe
    public interface Builder extends SdkPojo, CopyableBuilder<Builder, AssumedRoleUser> {
        /**
         * <p>
         * A unique identifier that contains the role ID and the role session name of the role that is being assumed.
         * The role ID is generated by Amazon Web Services when the role is created.
         * </p>
         *
         * @param assumedRoleId
         *        A unique identifier that contains the role ID and the role session name of the role that is being
         *        assumed. The role ID is generated by Amazon Web Services when the role is created.
         * @return Returns a reference to this object so that method calls can be chained together.
         */
        Builder assumedRoleId(String assumedRoleId);

        /**
         * <p>
         * The ARN of the temporary security credentials that are returned from the <a>AssumeRole</a> action. For more
         * information about ARNs and how to use them in policies, see <a
         * href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html">IAM Identifiers</a> in the
         * <i>IAM User Guide</i>.
         * </p>
         *
         * @param arn
         *        The ARN of the temporary security credentials that are returned from the <a>AssumeRole</a> action. For
         *        more information about ARNs and how to use them in policies, see <a
         *        href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html">IAM Identifiers</a>
         *        in the <i>IAM User Guide</i>.
         * @return Returns a reference to this object so that method calls can be chained together.
         */
        Builder arn(String arn);
    }

    static final class BuilderImpl implements Builder {
        private String assumedRoleId;

        private String arn;

        private BuilderImpl() {
        }

        private BuilderImpl(AssumedRoleUser model) {
            assumedRoleId(model.assumedRoleId);
            arn(model.arn);
        }

        public final String getAssumedRoleId() {
            return assumedRoleId;
        }

        public final void setAssumedRoleId(String assumedRoleId) {
            this.assumedRoleId = assumedRoleId;
        }

        @Override
        public final Builder assumedRoleId(String assumedRoleId) {
            this.assumedRoleId = assumedRoleId;
            return this;
        }

        public final String getArn() {
            return arn;
        }

        public final void setArn(String arn) {
            this.arn = arn;
        }

        @Override
        public final Builder arn(String arn) {
            this.arn = arn;
            return this;
        }

        @Override
        public AssumedRoleUser build() {
            return new AssumedRoleUser(this);
        }

        @Override
        public List<SdkField<?>> sdkFields() {
            return SDK_FIELDS;
        }

        @Override
        public Map<String, SdkField<?>> sdkFieldNameToField() {
            return SDK_NAME_TO_FIELD;
        }
    }
}
